### ISSUE TITLE
Can't make a room, can't be invited as speaker, can't add anything

### ISSUE THREAD

**Issue by lanalabinsta** [grishka/Houseclub#141]
**Describe the bug**
Nothing works. I only could hear other rooms, but can't make my own room, can't see settings, don't see avatars, and can't add mine.

Basically the only bitton I have is logout, and leave the room. Button wave have, but it's not working.

I add screenshots how it looks like, and info about my phone.
![Screenshot_2021-02-23-20-35-59-764_com android settings](https://user-images.githubusercontent.com/79528751/108891046-ecda0000-7616-11eb-8c65-9944a8bf5b5a.jpg)
![Screenshot_2021-02-23-20-31-18-537_me grishka houseclub](https://user-images.githubusercontent.com/79528751/108891056-ef3c5a00-7616-11eb-8a57-abff917b4abc.jpg)
![Screenshot_2021-02-23-20-31-30-853_me grishka houseclub](https://user-images.githubusercontent.com/79528751/108891066-f1061d80-7616-11eb-8ad6-79ffc8f04dd5.jpg)

Thanks 👍

**Comment by tustoz** [comment]
I will help answer your questions. yes, you can only join other rooms, but cannot create new rooms. this is because That part of the API is marked as "unstable" at [this Clubhouse API](https://github.com/stypr/clubhouse-py)     python project. If you ask why you can't change your avatar, just tap on the avatar and you will immediately be prompted to select a photo from the gallery. there is a little bug for the wave button but it will be fixed soon

**Comment by grishka** [comment]
It doesn't work, because... wait for it... **it isn't implemented**. The code to do it hasn't been written. It's that simple.
