### ISSUE TITLE
My account has been suspended 

### ISSUE THREAD

**Issue by a7md-dot** [grishka/Houseclub#214]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - OS: [e.g. Android 11]
 - Version [e.g. 1.0.7]

**Additional context**
![Screenshot_20210301_200653_ru turbominer houseclub](https://user-images.githubusercontent.com/79813233/109542137-58b3e100-7acd-11eb-8abb-454ec3143420.jpg)

**Comment by Boludoskies** [comment]
+1 Also had my account suspended

**Comment by imrankhairuddin** [comment]
+1 Also had my account suspended

**Comment by raciard** [comment]
+1 Also had my account suspended

**Comment by grishka** [comment]
You were warned about this when you created your account through the app. This is not an issue with the app.

**Comment by Ahmad90kw** [comment]
> You were warned about this when you created your account through the app. This is not an issue with the app.
This is also not because it is an android edition it has nothing to do with that. 

This is because you have been spamming the app with either a fake name or with a fake picture and your behavior on app is not normal even if u had a. IPhone this will happen. But this has nothing to do with programming and has nothing to do with Android phones
